/**
 * Mechanical SVG extraction — the visual half of the parity story.
 *
 * The native app must draw the *same* geometry the web app draws, not a hand-redrawn
 * approximation. Rather than retyping path data (where drift creeps in), this script parses the web
 * sources and emits everything the renderer needs — geometry, inherited paint, composed transforms,
 * gradients, clip paths and the variant-dependent paints — into a generated Kotlin file the Compose
 * layer consumes.
 *
 * Sources parsed (every file in src/ that contains an <svg>):
 *   src/components/ui/Icons.tsx      — the 34 icons in the PATHS map (+ { ...S } spread defaults)
 *   src/components/hub/Glyphs.tsx    — the seven hub-node glyphs (ConfigGlyph's gear paths are
 *                                      generated by a function in that file, so it is evaluated)
 *   src/components/hub/Wireframe.tsx — the 24 backdrop curves + rings
 *   src/components/hub/TopBar.tsx    — the up-arrow logo (with its gradient)
 *   src/components/hub/Chains.tsx    — the chain tile, an SVG data-URI with three gradients
 *   src/components/ui/Art.tsx        — the disc fallback artwork
 *   src/components/MascotFace.tsx    — the mascot: 4 gradients, 2 clip paths, yellow/mono variants
 *
 * What "parsed" means here: a small JSX-subset reader (tags, attributes, string/`{expr}` values,
 * fragments, comments, nesting) plus resolvers for the three dynamic patterns these files actually
 * use — `url(#${id}x)` from React's useId(), variant ternaries (`const ink = yellow ? A : B`,
 * `const stops = yellow ? […] : […]`) and locally-defined pure generator functions. Anything else
 * throws, so the generated file can never silently lose a curve.
 *
 * Output: android/app/src/main/kotlin/com/thegadget/app/ui/SvgPaths.kt  (generated, committed)
 *
 * Usage: node verification/extract-svg.mjs [--check]
 *        --check  fail (exit 1) if the generated file differs from what is on disk
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "android/app/src/main/kotlin/com/thegadget/app/ui/SvgPaths.kt");
const CHECK = process.argv.includes("--check");
/** True when executed directly; false when imported (gen-path-vectors.mjs reuses extractAll). */
const IS_MAIN = process.argv[1] ? path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url)) : false;
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");

/* ------------------------------------------------------------- JSX-subset reader */

const VOID = new Set(["stop", "path", "circle", "ellipse", "rect", "line", "polygon", "polyline", "use", "image"]);
const DRAWABLE = new Set(["path", "circle", "ellipse", "rect", "line", "polygon", "polyline", "text"]);

/** Index of the `}` matching the `{` at `i`, ignoring braces inside quotes/template literals. */
function matchBrace(src, i) {
  let depth = 0;
  let quote = null;
  for (let j = i; j < src.length; j++) {
    const c = src[j];
    if (quote) {
      if (c === "\\") j++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") quote = c;
    else if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) return j;
    }
  }
  throw new Error("unbalanced { in JSX");
}

/** Index of the `>` that closes the tag starting at `from`. */
function findTagEnd(src, from) {
  let quote = null;
  let depth = 0;
  for (let j = from + 1; j < src.length; j++) {
    const c = src[j];
    if (quote) {
      if (c === "\\") j++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") quote = c;
    else if (c === "{") depth++;
    else if (c === "}") depth--;
    else if (c === ">" && depth === 0) return j;
  }
  throw new Error(`unterminated tag near: ${src.slice(from, from + 60)}`);
}

const tagName = (tagSrc) => (tagSrc.match(/^[A-Za-z0-9_.>-]+/) || [""])[0];

/** `d="M0 0" fill={ink} {...S}` → { d: {literal}, fill: {expr}, "…S": {spread: "S"} } */
function parseAttrs(tagSrc) {
  const attrs = {};
  let i = 0;
  while (i < tagSrc.length) {
    while (i < tagSrc.length && /\s/.test(tagSrc[i])) i++;
    if (i >= tagSrc.length) break;
    const start = i;
    while (i < tagSrc.length && /[A-Za-z0-9_:.\-$]/.test(tagSrc[i])) i++;
    const name = tagSrc.slice(start, i);
    if (!name) { i++; continue; }
    if (name.startsWith("...")) {
      attrs[name] = { spread: name.slice(3) };
      continue;
    }
    if (tagSrc[i] !== "=") {
      attrs[name] = { literal: "true" };
      continue;
    }
    i++;
    if (tagSrc[i] === '"' || tagSrc[i] === "'") {
      const q = tagSrc[i];
      const s = ++i;
      while (i < tagSrc.length && tagSrc[i] !== q) i++;
      attrs[name] = { literal: tagSrc.slice(s, i) };
      i++;
    } else if (tagSrc[i] === "{") {
      const end = matchBrace(tagSrc, i);
      attrs[name] = { expr: tagSrc.slice(i + 1, end) };
      i = end + 1;
    } else {
      const s = i;
      while (i < tagSrc.length && !/[\s>]/.test(tagSrc[i])) i++;
      attrs[name] = { literal: tagSrc.slice(s, i) };
    }
  }
  return attrs;
}

/** Text of the element closed by `</name>`, plus the index just past that close tag. */
function sliceUntilClose(src, from, name) {
  let i = from;
  let depth = 1;
  while (i < src.length) {
    const c = src[i];
    if (c === "{") {
      i = matchBrace(src, i) + 1;
      continue;
    }
    if (c === "<") {
      if (src.startsWith("<!--", i)) {
        const e = src.indexOf("-->", i);
        i = e < 0 ? src.length : e + 3;
        continue;
      }
      if (src.startsWith("</", i)) {
        const end = src.indexOf(">", i);
        if (src.slice(i + 2, end).trim() === name) {
          depth--;
          if (depth === 0) return { text: src.slice(from, i), end: end + 1 };
        }
        i = end + 1;
        continue;
      }
      const end = findTagEnd(src, i);
      const tagSrc = src.slice(i + 1, end);
      if (tagName(tagSrc) === name && !tagSrc.trimEnd().endsWith("/")) depth++;
      i = end + 1;
      continue;
    }
    i++;
  }
  throw new Error(`missing </${name}>`);
}

/**
 * Parse a JSX region into a node tree. Expression blocks (`{cond && (…)}`, `{list.map(…)}`,
 * `{value}`) are kept as `expr` nodes; any JSX inside one is parsed too, because the sources use
 * those blocks to hold real drawing content.
 */
function parseChildren(src) {
  const nodes = [];
  let i = 0;
  while (i < src.length) {
    const c = src[i];
    if (c === "<") {
      if (src.startsWith("<!--", i)) {
        const e = src.indexOf("-->", i);
        i = e < 0 ? src.length : e + 3;
        continue;
      }
      if (src.startsWith("</", i)) break;
      const end = findTagEnd(src, i);
      const tagSrc = src.slice(i + 1, end);
      const name = tagName(tagSrc);
      const selfClosing = tagSrc.trimEnd().endsWith("/") || VOID.has(name);
      const attrSrc = tagSrc.slice(name.length).replace(/\/\s*$/, "");
      const node = { kind: "el", tag: name, attrs: parseAttrs(attrSrc), children: [] };
      i = end + 1;
      if (!selfClosing) {
        const inner = sliceUntilClose(src, i, name);
        node.children = parseChildren(inner.text);
        i = inner.end;
      }
      nodes.push(node);
      continue;
    }
    if (c === "{") {
      if (src.startsWith("{/*", i)) {
        const e = src.indexOf("*/}", i);
        i = e < 0 ? src.length : e + 3;
        continue;
      }
      const end = matchBrace(src, i);
      const code = src.slice(i + 1, end);
      const node = { kind: "expr", code, children: [] };
      const jsx = code.search(/<[A-Za-z>]/);
      if (jsx >= 0) node.children = parseChildren(code.slice(jsx));
      nodes.push(node);
      i = end + 1;
      continue;
    }
    let j = i;
    while (j < src.length && src[j] !== "<" && src[j] !== "{") j++;
    const text = src.slice(i, j);
    if (text.trim()) nodes.push({ kind: "text", value: text.trim() });
    i = j;
  }
  return nodes;
}

/** The first `<svg …>` in a region, as { root, children } — or null. */
function parseSvg(region) {
  const at = region.indexOf("<svg");
  if (at < 0) return null;
  const end = findTagEnd(region, at);
  const tagSrc = region.slice(at + 1, end);
  const inner = sliceUntilClose(region, end + 1, "svg");
  return {
    root: { tag: "svg", attrs: parseAttrs(tagSrc.slice(3)), children: [] },
    children: parseChildren(inner.text),
  };
}

/* ------------------------------------------------------------- component bodies */

/** Bodies of `[export] function Name(…) { … }`. */
function functionComponents(source) {
  const out = [];
  const re = /(?:export\s+)?function\s+([A-Za-z0-9_]+)\s*\([^)]*\)\s*\{/g;
  let m;
  while ((m = re.exec(source))) {
    const open = re.lastIndex - 1;
    const end = matchBrace(source, open);
    out.push({ name: m[1], body: source.slice(open + 1, end) });
  }
  return out;
}

/** Bodies of `const Name = (…) => ( … );` / `=> { … }`. */
function arrowComponents(source) {
  const out = [];
  const re = /const\s+([A-Z][A-Za-z0-9_]*)\s*(?::[^=]+)?=\s*\(([^)]*)\)\s*=>\s*/g;
  let m;
  while ((m = re.exec(source))) {
    let i = re.lastIndex;
    let body;
    if (source[i] === "{") {
      const end = matchBrace(source, i);
      body = source.slice(i + 1, end);
    } else {
      // expression body: read to the matching `);` at depth 0
      let depth = 0;
      let quote = null;
      let j = i;
      for (; j < source.length; j++) {
        const c = source[j];
        if (quote) {
          if (c === "\\") j++;
          else if (c === quote) quote = null;
          continue;
        }
        if (c === '"' || c === "'" || c === "`") quote = c;
        else if ("([{".includes(c)) depth++;
        else if (")]}".includes(c)) {
          depth--;
          if (depth === 0) break;
        }
      }
      body = source.slice(i, j);
    }
    out.push({ name: m[1], body });
  }
  return out;
}

/* ------------------------------------------------------------- dynamic values */

/**
 * Values the sources compute instead of writing literally. Each resolver throws rather than
 * returning a guess: a missing curve is worse than a loud failure.
 */
function variantTokens(body) {
  const tokens = {};
  const re = /const\s+([A-Za-z_$][\w$]*)\s*=\s*yellow\s*\?\s*"([^"]+)"\s*:\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(body))) tokens[m[1]] = { yellow: m[2], mono: m[3] };
  return tokens;
}

function variantStops(body) {
  const m = body.match(/const\s+stops\s*=\s*yellow\s*\?\s*(\[\[[\s\S]*?\]\])\s*:\s*(\[\[[\s\S]*?\]\])/);
  if (!m) return null;
  return { yellow: JSON.parse(m[1]), mono: JSON.parse(m[2]) };
}

/**
 * ConfigGlyph builds its two gear paths with a local `gear(…)` helper. Running the real function
 * is the only way to get the same `d` the browser gets, so the local arrow functions of the
 * component are lifted into an evaluator. Expressions are restricted to a safe charset.
 */
function localEvaluator(body) {
  const fns = [];
  const re = /const\s+([A-Za-z_$][\w$]*)\s*=\s*\(([^)]*)\)\s*=>\s*\{/g;
  let m;
  while ((m = re.exec(body))) {
    const end = matchBrace(body, re.lastIndex - 1);
    fns.push(body.slice(m.index, end + 1));
    re.lastIndex = end;
  }
  if (!fns.length) return null;
  // The sources are TypeScript, so strip the type annotations with the same esbuild the web build
  // uses before evaluating — hand-rolled type stripping would silently diverge on the first
  // non-trivial signature.
  const prelude = execFileSync(path.join(ROOT, "node_modules/esbuild/bin/esbuild"), ["--loader=ts"], {
    input: fns.join("\n"),
    encoding: "utf8",
  });
  return (expr) => {
    if (!/^[\w$.\s,()*/+-]*$/.test(expr)) throw new Error(`refusing to evaluate {${expr}}`);
    return new Function(`${prelude}\nreturn (${expr});`)();
  };
}

/* ------------------------------------------------------------- attribute handling */

const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

/** Presentation attributes that SVG inherits down the tree. */
const INHERITED = [
  "fill", "fillOpacity", "fillRule", "stroke", "strokeWidth", "strokeOpacity",
  "strokeLinecap", "strokeLinejoin", "clipPath",
];
/** Everything SvgElement can carry (camelCased). */
const KEPT = [
  "d", "cx", "cy", "r", "rx", "ry", "x", "y", "x1", "y1", "x2", "y2", "width", "height", "points",
  ...INHERITED, "opacity", "transform", "className", "textAnchor", "fontSize", "fontFamily",
];

/** Attributes that exist for the DOM/a11y and have no meaning to a Canvas renderer. */
const IGNORED = new Set([
  "ariaHidden", "focusable", "key", "decoding", "draggable", "alt", "xmlns", "preserveAspectRatio",
  "version", "role", "tabIndex", "loading", "crossOrigin",
]);

function resolveValue(spec, ctx, where) {
  if (spec.literal !== undefined) return spec.literal.trim();
  const e = (spec.expr ?? "").trim();
  if (/^"([^"]*)"$/.test(e) || /^'([^']*)'$/.test(e)) return e.slice(1, -1);
  if (e.startsWith("`") && e.endsWith("`")) {
    const body = e.slice(1, -1);
    if (!body.includes("${")) return body;
    // React's useId() prefix: `${id}f` → the group-namespaced gradient/clip id.
    const resolved = body.replace(/\$\{\s*id\s*\}/g, `${ctx.ns}.`);
    if (resolved.includes("${")) throw new Error(`${where}: cannot resolve template {${e}}`);
    return resolved;
  }
  if (/^-?[\d.]+$/.test(e)) return e;
  if (/^[A-Za-z_$][\w$]*$/.test(e)) {
    if (ctx.tokens[e]) return `token:${e}`;
    throw new Error(`${where}: cannot resolve identifier {${e}}`);
  }
  if (/^[A-Za-z_$][\w$]*\(/.test(e) && ctx.evaluate) {
    const value = ctx.evaluate(e);
    if (value !== undefined && value !== null) return String(value);
  }
  if (/^cx\(/.test(e)) {
    const parts = [...e.matchAll(/"([^"]*)"/g)].map((m) => m[1]);
    if (parts.length) return parts.join(" ");
  }
  throw new Error(`${where}: cannot resolve attribute value {${e}}`);
}

/**
 * Resolved attribute map. `only` restricts to SvgElement's fields; structural elements (the <svg>
 * root, gradients, clip paths) resolve everything they carry. Non-presentation attributes that the
 * renderer has no use for (aria-*, focusable, key, decoding…) are ignored.
 */
function resolveAttrs(node, ctx, where, only = null) {
  const out = {};
  for (const [rawName, spec] of Object.entries(node.attrs)) {
    if (spec.spread) {
      for (const [k, v] of Object.entries(ctx.spreads[spec.spread] || {})) out[camel(k)] = v;
      continue;
    }
    const name = camel(rawName);
    if (IGNORED.has(name)) continue;
    if (only && !only.includes(name)) continue;
    try {
      out[name] = resolveValue(spec, ctx, `${where} ${rawName}`);
    } catch (err) {
      // `className={className}` on every root <svg>: the class comes from the call site, so the
      // group simply carries no static one. Every other unresolved value stays an error.
      if (name === "className" && /^[A-Za-z_$][\w$]*$/.test((spec.expr ?? "").trim())) continue;
      throw err;
    }
  }
  return out;
}

/* ------------------------------------------------------------- defs */

/** `44%` → 0.44, `0.44` → 0.44 (SVG gradientUnits defaults to objectBoundingBox). */
function gradientCoord(v) {
  if (v === undefined || v === null) return null;
  const s = String(v).trim();
  return s.endsWith("%") ? Number(s.slice(0, -1)) / 100 : Number(s);
}

function stopElements(node, ctx, where) {
  const stops = [];
  let variantStopsFound = null;
  for (const child of node.children) {
    if (child.kind === "expr") {
      if (/stops\s*\.\s*map/.test(child.code)) {
        variantStopsFound = ctx.variantStops;
        continue;
      }
      throw new Error(`${where}: unexpected expression inside <${node.tag}>: {${child.code.slice(0, 40)}}`);
    }
    if (child.kind !== "el" || child.tag !== "stop") continue;
    const a = resolveAttrs(child, ctx, `${where} stop`);
    stops.push({
      offset: Number(a.offset ?? 0),
      color: a.stopColor ?? a.color ?? "#000",
      opacity: a.stopOpacity === undefined ? 1 : Number(a.stopOpacity),
    });
  }
  return { stops, variantStopsFound };
}

function parseDefs(nodes, ctx) {
  const gradients = [];
  const clips = [];
  const walk = (list) => {
    for (const n of list) {
      if (n.kind !== "el") continue;
      if (n.tag === "linearGradient" || n.tag === "radialGradient") {
        const a = resolveAttrs(n, ctx, `defs ${n.tag}`);
        const id = a.id ?? throw_(`${n.tag} without id`);
        const { stops, variantStopsFound } = stopElements(n, ctx, `defs ${n.tag}`);
        const geom = {
          x1: gradientCoord(a.x1), y1: gradientCoord(a.y1),
          x2: gradientCoord(a.x2), y2: gradientCoord(a.y2),
          cx: gradientCoord(a.cx), cy: gradientCoord(a.cy), r: gradientCoord(a.r),
        };
        if (variantStopsFound) {
          for (const variant of ["yellow", "mono"]) {
            gradients.push({
              id, kind: n.tag === "radialGradient" ? "radial" : "linear", ...geom, variant,
              stops: variantStopsFound[variant].map(([o, c]) => ({ offset: Number(o), color: c, opacity: 1 })),
            });
          }
        } else {
          if (stops.length < 2) throw_(`gradient ${id} has ${stops.length} stops`);
          gradients.push({ id, kind: n.tag === "radialGradient" ? "radial" : "linear", ...geom, stops });
        }
      } else if (n.tag === "clipPath") {
        const a = resolveAttrs(n, ctx, "defs clipPath");
        const id = a.id ?? throw_("clipPath without id");
        const elements = [];
        flatten(n.children, { ...ctx, inClip: true }, elements);
        clips.push({ id, elements });
      } else {
        walk(n.children);
      }
    }
  };
  walk(nodes);
  return { gradients, clips };
}

const throw_ = (msg) => {
  throw new Error(msg);
};

/* ------------------------------------------------------------- flattening */

/**
 * Walk the drawing tree, emitting one flat record per primitive with the presentation attributes
 * the browser would have resolved for it: ancestor paint inherited, transforms composed in order,
 * the nearest clip path remembered, and the class names accumulated (they drive the CSS
 * animations the native layer reproduces).
 */
function flatten(nodes, ctx, out) {
  for (const n of nodes) {
    if (n.kind === "text") {
      if (ctx.textTarget) ctx.textTarget.text = n.value;
      continue;
    }
    if (n.kind === "expr") {
      flatten(n.children, ctx, out);
      continue;
    }
    if (n.tag === "defs") continue;

    const own = resolveAttrs(n, ctx, `<${n.tag}>`, n.tag === "g" || n.tag === "svg" ? null : KEPT);
    const where = `<${n.tag}>`;

    if (n.tag === "g" || n.tag === "svg") {
      const child = {
        ...ctx,
        paint: { ...ctx.paint },
        transform: [...ctx.transform],
        classes: [...ctx.classes],
      };
      for (const k of INHERITED) if (own[k] !== undefined) child.paint[k] = own[k];
      if (own.transform) child.transform.push(own.transform);
      if (own.className) child.classes.push(own.className);
      if (own.clipPath) child.clipPath = own.clipPath;
      flatten(n.children, child, out);
      continue;
    }

    if (!DRAWABLE.has(n.tag)) {
      flatten(n.children, ctx, out);
      continue;
    }

    const el = { kind: n.tag };
    for (const k of KEPT) {
      if (own[k] !== undefined) el[k] = own[k];
      else if (INHERITED.includes(k) && ctx.paint[k] !== undefined) el[k] = ctx.paint[k];
    }
    const transform = [...ctx.transform, ...(own.transform ? [own.transform] : [])];
    if (transform.length) el.transform = transform.join(" ");
    const classes = [...ctx.classes, ...(own.className ? [own.className] : [])];
    if (classes.length) el.className = classes.join(" ");
    const clip = own.clipPath ?? ctx.clipPath;
    if (clip) el.clipPath = clip;
    if (n.tag === "text") {
      el.text = "";
      for (const child of n.children) if (child.kind === "expr") el.text = `{${child.code.trim()}}`;
      else if (child.kind === "text") el.text = child.value;
    }
    out.push(el);
    flatten(n.children, ctx, out);
  }
}

/* ------------------------------------------------------------- sources */

/** Icons.tsx: a `PATHS` record of `name: <path … />` entries with a `{ ...S }` spread. */
function iconGroups() {
  const source = read("src/components/ui/Icons.tsx");
  const spreadSrc = source.match(/const\s+S\s*=\s*\{([^}]*)\}/);
  const spreads = { S: {} };
  if (spreadSrc) {
    for (const part of spreadSrc[1].split(",")) {
      const [k, v] = part.split(":").map((s) => s && s.trim().replace(/^["']|["']$/g, ""));
      if (k && v) spreads.S[camel(k)] = v;
    }
  }
  // The defaults the <svg> in Icon() carries apply to every icon.
  const icon = functionComponents(source).find((c) => c.name === "Icon");
  const root = parseSvg(icon.body).root;
  const rootAttrs = resolveAttrs(root, { ns: "icon", tokens: {}, spreads, evaluate: null, variantStops: null }, "<svg>");
  const meta = {
    viewBox: rootAttrs.viewBox ?? "0 0 24 24",
    strokeWidth: rootAttrs.strokeWidth ?? null,
    strokeLinecap: rootAttrs.strokeLinecap ?? null,
    strokeLinejoin: rootAttrs.strokeLinejoin ?? null,
    rootClassName: "ico",
  };

  const start = source.indexOf("const PATHS");
  const region = source.slice(start, source.indexOf("\n};", start));
  const out = [];
  const re = /^\s{2}(?:"([^"]+)"|([A-Za-z0-9_-]+))\s*:\s*([\s\S]*?),\s*$/gm;
  let m;
  while ((m = re.exec(region))) {
    const name = m[1] ?? m[2];
    const nodes = parseChildren(m[3]);
    const elements = [];
    flatten(nodes, { ns: "icon", paint: {}, transform: [], classes: [], tokens: {}, spreads, evaluate: null, variantStops: null }, elements);
    if (!elements.length) throw new Error(`icon "${name}" produced no elements`);
    out.push([`icon.${name}`, { ...meta }, elements]);
  }
  return out;
}

/** One group per SVG-bearing component in a file. */
function componentGroups(file, prefix, { arrow = false } = {}) {
  const source = read(file);
  const bodies = [...functionComponents(source), ...(arrow ? arrowComponents(source) : [])];
  const out = [];
  for (const { name, body } of bodies) {
    const svg = parseSvg(body);
    if (!svg) continue;
    const ns = prefix;
    const tokens = variantTokens(body);
    const ctx = {
      ns,
      paint: {},
      transform: [],
      classes: [],
      tokens,
      spreads: {},
      evaluate: localEvaluator(body),
      variantStops: variantStops(body),
    };
    const rootAttrs = resolveAttrs(svg.root, ctx, "<svg>");
    const { gradients, clips } = parseDefs(svg.children, ctx);
    const elements = [];
    flatten(svg.children, ctx, elements);
    if (!elements.length && !gradients.length) continue;
    out.push([
      `${prefix}.${name}`,
      {
        viewBox: rootAttrs.viewBox ?? null,
        rootClassName: rootAttrs.className ?? null,
        fill: rootAttrs.fill ?? null,
        stroke: rootAttrs.stroke ?? null,
        strokeWidth: rootAttrs.strokeWidth ?? null,
        strokeLinecap: rootAttrs.strokeLinecap ?? null,
        strokeLinejoin: rootAttrs.strokeLinejoin ?? null,
        gradients,
        clips,
        tokens: Object.fromEntries(Object.entries(tokens).flatMap(([k, v]) => Object.entries(v).map(([variant, color]) => [`${k}.${variant}`, color]))),
      },
      elements,
    ]);
  }
  return out;
}

/** Chains.tsx keeps its tile in an SVG data-URI template literal — parse that string directly. */
function chainGroups() {
  const source = read("src/components/hub/Chains.tsx");
  const from = source.indexOf("<svg");
  const to = source.indexOf("</svg>", from);
  if (from < 0 || to < 0) throw new Error("Chains.tsx: no SVG tile found");
  const svg = parseSvg(source.slice(from, to + 6));
  const ctx = { ns: "chain", paint: {}, transform: [], classes: [], tokens: {}, spreads: {}, evaluate: null, variantStops: null };
  const rootAttrs = resolveAttrs(svg.root, ctx, "<svg>");
  const { gradients, clips } = parseDefs(svg.children, ctx);
  const elements = [];
  flatten(svg.children, ctx, elements);
  return [[
    "chain.tile",
    {
      viewBox: rootAttrs.viewBox,
      width: rootAttrs.width ?? null,
      height: rootAttrs.height ?? null,
      gradients,
      clips,
      tokens: {},
    },
    elements,
  ]];
}

/* ------------------------------------------------------------- emitting */

const NUMERIC = new Set(["cx", "cy", "r", "rx", "ry", "x", "y", "x1", "y1", "x2", "y2", "width", "height"]);
const num = (v) => `${Number(v)}f`;
const kstr = (v) => `"${String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;

function emitElement(el, indent = "            ") {
  const parts = [`kind = ${kstr(el.kind)}`];
  for (const [k, v] of Object.entries(el)) {
    if (k === "kind") continue;
    parts.push(NUMERIC.has(k) ? `${k} = ${num(v)}` : `${k} = ${kstr(v)}`);
  }
  return `${indent}SvgElement(${parts.join(", ")}),`;
}

function emitGradient(g) {
  const parts = [`id = ${kstr(g.id)}`, `kind = ${kstr(g.kind)}`];
  for (const k of ["x1", "y1", "x2", "y2", "cx", "cy", "r"]) if (g[k] !== null && g[k] !== undefined) parts.push(`${k} = ${num(g[k])}`);
  if (g.variant) parts.push(`variant = ${kstr(g.variant)}`);
  parts.push(`stops = listOf(\n${g.stops.map((s) => `                SvgStop(offset = ${num(s.offset)}, color = ${kstr(s.color)}, opacity = ${num(s.opacity)}),`).join("\n")}\n            )`);
  return `            SvgGradient(${parts.join(", ")}),`;
}

function emitGroup([name, meta, elements]) {
  const settings = [`name = ${kstr(name)}`];
  if (meta.viewBox) settings.push(`viewBox = ${kstr(meta.viewBox)}`);
  if (meta.rootClassName) settings.push(`rootClassName = ${kstr(meta.rootClassName)}`);
  if (meta.width) settings.push(`width = ${num(meta.width)}`);
  if (meta.height) settings.push(`height = ${num(meta.height)}`);
  if (meta.strokeWidth) settings.push(`strokeWidth = ${num(meta.strokeWidth)}`);
  if (meta.strokeLinecap) settings.push(`strokeLinecap = ${kstr(meta.strokeLinecap)}`);
  if (meta.strokeLinejoin) settings.push(`strokeLinejoin = ${kstr(meta.strokeLinejoin)}`);
  if (meta.fill) settings.push(`fill = ${kstr(meta.fill)}`);
  if (meta.stroke) settings.push(`stroke = ${kstr(meta.stroke)}`);
  if (meta.gradients?.length) settings.push(`gradients = listOf(\n${meta.gradients.map(emitGradient).join("\n")}\n        )`);
  if (meta.clips?.length) {
    settings.push(`clips = listOf(\n${meta.clips.map((c) => `            SvgClip(id = ${kstr(c.id)}, elements = listOf(\n${c.elements.map((e) => emitElement(e, "                ")).join("\n")}\n            )),`).join("\n")}\n        )`);
  }
  if (meta.tokens && Object.keys(meta.tokens).length) {
    settings.push(`tokens = mapOf(\n${Object.entries(meta.tokens).map(([k, v]) => `            ${kstr(k)} to ${kstr(v)},`).join("\n")}\n        )`);
  }
  return `    SvgGroup(\n        ${settings.join(",\n        ")},\n        elements = listOf(\n${elements.map((e) => emitElement(e)).join("\n")}\n        ),\n    ),`;
}

/** Everything the extractor finds — reused by the path-sampling vector builder. */
export function extractAll() {
  const groups = [
    ...iconGroups(),
    ...componentGroups("src/components/hub/Glyphs.tsx", "glyph"),
    ...componentGroups("src/components/hub/Wireframe.tsx", "wire"),
    ...componentGroups("src/components/hub/TopBar.tsx", "top"),
    ...componentGroups("src/components/ui/Art.tsx", "art", { arrow: true }),
    ...componentGroups("src/components/MascotFace.tsx", "mascot"),
    ...chainGroups(),
  ];
  groups.sort((a, b) => a[0].localeCompare(b[0]));
  return groups;
}

const HEADER = `package com.thegadget.app.ui

// GENERATED FILE — do not edit by hand.
// Produced by verification/extract-svg.mjs from the web sources, so every curve the native app
// draws is byte-identical to the SVG the browser renders. Re-generate with:
//     node verification/extract-svg.mjs
// Freshness is enforced by \`node verification/extract-svg.mjs --check\`; geometry is checked
// against the browser by the \`paths\` block of verification/RunVectors.kt.
//
// sources: src/components/{ui/Icons.tsx, hub/Glyphs.tsx, hub/Wireframe.tsx, hub/TopBar.tsx,
//          hub/Chains.tsx, ui/Art.tsx, MascotFace.tsx}
`;

const MODEL = `
/** One gradient stop. \`offset\` is 0..1 along the gradient vector/radius. */
data class SvgStop(val offset: Float, val color: String, val opacity: Float = 1f)

/**
 * A gradient from a <defs> block. Coordinates are objectBoundingBox fractions (SVG's default
 * gradientUnits), i.e. \`cx = 0.44f\` means 44% across the painted shape's bounds — which is what
 * the browser resolves \`cx="44%"\` to. [variant] is non-null only for the mascot face, whose
 * paints depend on its yellow/mono variant.
 */
data class SvgGradient(
    val id: String,
    val kind: String,
    val x1: Float? = null,
    val y1: Float? = null,
    val x2: Float? = null,
    val y2: Float? = null,
    val cx: Float? = null,
    val cy: Float? = null,
    val r: Float? = null,
    val variant: String? = null,
    val stops: List<SvgStop> = emptyList(),
)

/** A <clipPath>: the shapes whose union clips the elements referencing it by id. */
data class SvgClip(val id: String, val elements: List<SvgElement>)

/**
 * One SVG primitive with every attribute the browser would have resolved for it: ancestor paint
 * inherited, transforms composed, the nearest clip remembered, class names accumulated.
 *
 * Paint values are SVG paint strings the renderer resolves against the gadget palette:
 * \`currentColor\`, \`#050505\`, \`var(--glyph-hole)\`, \`url(#mascot.f)\` (a gradient in the same
 * group), \`token:ink\` (a variant-dependent colour from [SvgGroup.tokens]) or \`none\`.
 */
data class SvgElement(
    val kind: String,
    val d: String? = null,
    val cx: Float? = null,
    val cy: Float? = null,
    val r: Float? = null,
    val rx: Float? = null,
    val ry: Float? = null,
    val x: Float? = null,
    val y: Float? = null,
    val x1: Float? = null,
    val y1: Float? = null,
    val x2: Float? = null,
    val y2: Float? = null,
    val width: Float? = null,
    val height: Float? = null,
    val points: String? = null,
    val fill: String? = null,
    val fillOpacity: String? = null,
    val fillRule: String? = null,
    val stroke: String? = null,
    val strokeWidth: String? = null,
    val strokeOpacity: String? = null,
    val strokeLinecap: String? = null,
    val strokeLinejoin: String? = null,
    val opacity: String? = null,
    /** Composed ancestor+self transform list, in SVG application order. */
    val transform: String? = null,
    /** Id of the [SvgClip] in the same group that clips this element, if any. */
    val clipPath: String? = null,
    /** Accumulated class names — the CSS-animated layers (\`mascot-eyes\`, \`wire-ring\`) key off these. */
    val className: String? = null,
    /** For kind = "text": the literal, or \`{name}\` when the web app interpolates a value. */
    val text: String? = null,
    val textAnchor: String? = null,
    val fontSize: String? = null,
    val fontFamily: String? = null,
)

/** A whole <svg>: primitives, definitions and the presentation defaults from the root element. */
data class SvgGroup(
    val name: String,
    val viewBox: String,
    val elements: List<SvgElement>,
    val rootClassName: String? = null,
    val width: Float? = null,
    val height: Float? = null,
    val strokeWidth: Float? = null,
    val strokeLinecap: String? = null,
    val strokeLinejoin: String? = null,
    val fill: String? = null,
    val stroke: String? = null,
    val gradients: List<SvgGradient> = emptyList(),
    val clips: List<SvgClip> = emptyList(),
    /** Variant-dependent paints, keyed \`<token>.<variant>\` — referenced as \`token:<token>\`. */
    val tokens: Map<String, String> = emptyMap(),
) {
    /** The gradient an element's \`url(#id)\` refers to, for the given mascot variant. */
    fun gradient(id: String, variant: String? = null): SvgGradient? =
        gradients.firstOrNull { it.id == id && (it.variant == null || it.variant == variant) }

    fun clip(id: String): SvgClip? = clips.firstOrNull { it.id == id }

    /** A variant-dependent colour: \`resolveToken("ink", "mono")\`. */
    fun resolveToken(token: String, variant: String): String? = tokens["$token.$variant"]
}
`;

function main() {
  const groups = extractAll();
  const digest = crypto
    .createHash("sha256")
    .update(JSON.stringify(groups))
    .digest("hex")
    .slice(0, 16);
  const elements = groups.reduce((n, [, , els]) => n + els.length, 0);
  const gradients = groups.reduce((n, [, meta]) => n + (meta.gradients?.length ?? 0), 0);
  const clips = groups.reduce((n, [, meta]) => n + (meta.clips?.length ?? 0), 0);

  const source = `${HEADER}// digest: ${digest}
// ${groups.length} groups, ${elements} elements, ${gradients} gradients, ${clips} clip paths
${MODEL}
object SvgPaths {
    const val DIGEST = "${digest}"

    /** Every extracted group: \`icon.play\`, \`glyph.ConfigGlyph\`, \`chain.tile\`, \`mascot.MascotFace\`, … */
    val groups: List<SvgGroup> = listOf(
${groups.map(emitGroup).join("\n")}
    )

    private val byName: Map<String, SvgGroup> = groups.associateBy { it.name }

    /** Exact lookup — a missing group is a bug in the extractor, never a silent fallback. */
    fun require(name: String): SvgGroup =
        byName[name] ?: error("no SVG group \\"$name\\" (generated groups: ${groups.size})")

    fun group(name: String): SvgGroup? = byName[name]

    val iconNames: List<String> = groups.map { it.name }.filter { it.startsWith("icon.") }.map { it.removePrefix("icon.") }

    /** The seven hub-node glyphs, by node id. */
    val glyphNames: List<String> = groups.map { it.name }.filter { it.startsWith("glyph.") }.map { it.removePrefix("glyph.") }
}
`;

  if (CHECK) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    const strip = (s) => s.replace(/digest: [0-9a-f]+/, "digest: x").replace(/const val DIGEST = "[0-9a-f]+"/, "const val DIGEST = x");
    if (strip(current) !== strip(source)) {
      console.error("SvgPaths.kt is out of date — run: node verification/extract-svg.mjs");
      process.exit(1);
    }
    console.log(`SvgPaths.kt up to date — ${groups.length} groups, ${elements} elements, ${gradients} gradients, ${clips} clips`);
    return;
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, source);
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
  console.log(`${groups.length} groups, ${elements} elements, ${gradients} gradients, ${clips} clip paths`);
  console.log(groups.map(([n, , els]) => `${n}(${els.length})`).join(", "));
}

if (IS_MAIN) main();
